on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: bash ./build.sh
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/games/ballblaster/ballblaster.cpp.hex
          build/games/jowst/jowst.cpp.hex
          build/games/pacman/pacman.cpp.hex
          build/games/titan/titan.cpp.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
